name: CI-Ubuntu
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: make print-COMPILE_FLAGS
      - run: make -j release
      - run: make -j test
      - run: make perft
