name: CI-Windows-Basic
on: [push]
jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: make -j4 release arch=basic
      - run: make -j4 test arch=basic
      - run: make perft arch=basic
