name: CI-Windows-CCRL-Optimized
on: [push]
jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: make print-COMPILE_FLAGS arch=znver3
      - run: make -j release arch=znver3
      - run: make -j test arch=znver3
      - run: make perft arch=znver3
