name: CI-Windows-no-BMI2
on: [push]
jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: make test
      - run: make release no-BMI2=1
      - run: make perft
