name: CI-Windows-Native
on: [push]
jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: make -j4 release
      - run: make -j4 test
      - run: make perft
