name: CI-Windows-Basic
on: [push]
jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: make print-COMPILE_FLAGS arch=basic
      - run: make -j release arch=basic
      - run: make -j test arch=basic
      - run: make perft arch=basic
