on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name of the release'
        required: true
        type: string
      version_number:
        description: 'E.g., v1.1.0'
        required: true
        type: string
      release_notes:
        description: 'Markdown for release note'
        required: true
        type: string
      

jobs:
  make-windows-release:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - run: make static=1 version=${{ inputs.version_number }} arch=znver3
    - run: mv bin/main/uci.exe rengar-${{ inputs.version_number }}$-CCRL.exe
    - uses: ncipollo/release-action@v1
      with:
        artifacts: rengar-${{ inputs.version_number }}$-CCRL.exe
        tag: ${{ inputs.version_number }}
        body: ${{ inputs.release_notes }}
